### ISSUE TITLE
Create professor version of the assignments page

### ISSUE THREAD

**Issue by ericgeil223** [logan-giese/whiteboard-course-management#51] opened 2021-06-30 00:02 UTC
Professor should be able to:
 

1. View all assignments that are in a course. 
2. Make new assignments.
3. View student submissions for each assignment per student. 
4. Assign a grade to a student's submission for each assignment.

**Comment by logan-giese** [comment] 2021-07-06 23:57
Possible duplicate of #62 ?

**Comment by logan-giese** [comment] 2021-07-20 23:23
This is now the One True Assignments Issue

**Closed as completed** 2021-07-29 23:05 UTC
Labels: enhancement
